## 01. NumPy
- 다차원 배열을 쉽고 효율적으로 사용할 수 있도록 지원하는 파이썬 라이브러리
- 데이터 분석 라이브러리의 근본

### 1-1 ndarray
- NumPy의 핵심 데이터 구조
- 동일한 자료형의 다차원 배열

In [ ]:
import numpy as np

In [ ]:
# ndarray 생성
a = np.array([[1,2,4], [4,5,6]])
b = np.array([1.0,2.3,3.14])

# 배열의 구조
print(f"배열의 구조 : {a.shape}")
# 배열의 구조 : (2, 3)

# 배열의 차원 수
print(f"배열의 차원 : {a.ndim}")
# 배열의 차원 : 2

# 데이터 타입
print(f"배열의 데이터 타입 : {a.dtype}")
print(f"배열의 데이터 타입 : {b.dtype}") 
# 배열의 데이터 타입 : int64 / 정수가 표현할 수 있는 용량 = 64 비트
# 배열의 데이터 타입 : float64 / 실수가 표현할 수 있는 용량 = 64 비트

# 형변환
new_a = a.astype(np.float64) 
print(f"배열의 데이터 타입 : {new_a.dtype}")
# 배열의 데이터 타입 : float64

In [ ]:
# 3차원 행열

a = np.array([[[1,2,4], [4,5,6]], [[1,2,4], [4,5,6]]])

print(f"배열의 구조 : {a.shape}")
print(f"배열의 차원 : {a.ndim}")
# 배열의 구조 : (2, 2, 3)
# 배열의 차원 : 3

In [ ]:
# 4차원 행열

a = np.array([[[[1,2,4], [4,5,6]], [[1,2,4], [4,5,6]]], [[[1,2,4], [4,5,6]], [[1,2,4], [4,5,6]]]])

print(f"배열의 구조 : {a.shape}")
print(f"배열의 차원 : {a.ndim}")
# 배열의 구조 : (2, 2, 2, 3)
# 배열의 차원 : 4

In [ ]:
# 만들 수 없는 배열

# 내부 배열의 구조가 같아야 함
a = np.array([[1], [2,3]]) # ValueError 

### 1-2 배열 초기화

In [ ]:
# 모든 요소가 0인 배열 생성

np.zeros((3, 4)) # 2차원
# array([[0., 0., 0., 0.],
#        [0., 0., 0., 0.],
#        [0., 0., 0., 0.]])

np.zeros((2, 3, 4), dtype=np.int64) # 3차원 / 데이터 타입 지정 가능
# array([[[0, 0, 0, 0],
#         [0, 0, 0, 0],
#         [0, 0, 0, 0]],

#        [[0, 0, 0, 0],
#         [0, 0, 0, 0],
#         [0, 0, 0, 0]]])

In [ ]:
# 모든 요소가 1인 배열 생성

np.ones((5,6))
# array([[1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1.]])

In [ ]:
# (원소의 값이) 초기화 되지 않은 배열 생성

np.empty((2,3)) # 쓰레기 값 = 메모리에 남아있던 값
# array([[4.9e-324, 9.9e-324, 2.0e-323],
#        [2.0e-323, 2.5e-323, 3.0e-323]])

In [ ]:
# 주어진 값으로 채운 배열

np.full((3,3), 7)
# array([[7, 7, 7],
#        [7, 7, 7],
#        [7, 7, 7]])

In [ ]:
# 단위 행렬 : 행렬의 곱에서 자기 자신이 만들어지는 행렬

np.eye(3,3)
# array([[1., 0., 0.],
#        [0., 1., 0.],
#        [0., 0., 1.]])

np.eye(3,5,1) # 3번째 인자를 입력하면 1이 오른쪽으로 이동
# array([[0., 1., 0., 0., 0.],
#        [0., 0., 1., 0., 0.],
#        [0., 0., 0., 1., 0.]])

### 1-3 범위 기반 배열 생성

In [ ]:
# arange : range() 와 유사한 기능을 제공
# 시작 이상 끝 미만의 정수 배열을 지정한 간격으로 생성

np.arange(0, 10)
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.arange(0, 10, 2)
# array([0, 2, 4, 6, 8])

In [ ]:
# linspace : 시작~끝까지 균일 간격으로 지정한 개수만큼 숫자를 생성
# 끝을 포함

np.linspace(10, 100, 10)
# array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

np.linspace(0.1, 1, 10)
# array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
# reshape : 배열의 구조를 재배치

np.linspace(1, 10, 6).reshape((2,3))
# array([[ 1. ,  2.8,  4.6],
#        [ 6.4,  8.2, 10. ]])

# 원소의 개수가 같아야 함
np.linspace(1, 10, 10).reshape((2,3)) # ValueError  

### 1-4 랜덤 배열 생성

In [ ]:
# random.rand(m, n) : 0~1 사이의 난수로 초기화

np.random.rand(2,3)
# array([[0.72780303, 0.82995047, 0.38476608],
#        [0.84412908, 0.29035368, 0.5260673 ]])

In [ ]:
# random.randn(m, n) : 표준정규분포를 따르는 난수로 초기화
# 표준정규분포 : 평균 : 0, 분산 : 1인 정규분포

np.random.randn(2,2,3)
# array([[[ 1.23783806,  1.0700067 ,  1.01619099],
#         [-1.26835453, -0.49229975,  1.59009656]],

#        [[ 1.84248661, -0.25435332, -1.44099114],
#         [ 0.00508073, -0.55274915, -0.24587321]]])

In [ ]:
# random.randint(low, high, (size)) : 정수 배열 생성

np.random.randint(0, 101, (3, 3))
# array([[36, 76, 50],
#        [32, 83, 34],
#        [33, 61,  3]])

In [ ]:
# random.seed() : 랜덤 난수의 초기화 값을 고정

np.random.seed(42)

print(np.random.rand(2,3))

print(np.random.randn(2,2))

print(np.random.randint(0, 101, (3, 3)))
# [[0.37454012 0.95071431 0.73199394]
#  [0.59865848 0.15601864 0.15599452]]

# [[ 1.57921282  0.76743473]
#  [-0.46947439  0.54256004]]

# [[63 59 20]
#  [32 75 57]
#  [21 88 48]]

In [ ]:
# RNG(Random Number Generator)
# 최근 파이썬 사용에서 권장되는 방식

from numpy.random import default_rng
rng = default_rng(seed=42)
rng2 = default_rng(seed=10) # 시드값 변경으로 독립적으로 시드 사용 가능
rng3 = default_rng() # 시드 사용 안해도 가능

# 0~1 사이의 난수
print(rng.random((2,3)))
# [[0.77395605 0.43887844 0.85859792]
#  [0.69736803 0.09417735 0.97562235]]

# 정규 분포
print(rng.normal(0, 1, (2,3)))
# [[ 0.1278404  -0.31624259 -0.01680116]
#  [-0.85304393  0.87939797  0.77779194]]

# 정수 난수
print(rng.integers(0, 100, (3,3)))
# [[78 64 40]
#  [82 54 44]
#  [45 22  9]]

# 균등 분포
print(rng.uniform(0, 100, (3,2)))
# [[ 6.38172561 82.7631172 ]
#  [63.16643991 75.80877401]
#  [35.45259681 97.06980244]]

In [ ]:
# 실습 1. 배열 초기화 및 생성

# 1. 
print(np.zeros((3,4)))

print(np.full((3,4), 5 ))

In [ ]:
# 2. 
np.arange(0, 21, 2)

In [ ]:
# 3. 
np.random.rand(2,3)

In [ ]:
# 4. 
from numpy.random import default_rng
rng = default_rng()
print(rng.normal(100,20,6))

In [ ]:
# 5.
np.arange(1, 21).reshape((4,5))

In [ ]:
# 6. 
np.linspace(0, 1, 12).reshape((3,4))

In [ ]:
# 7.
np.random.seed(42)
a = np.random.randint(0, 100, (10, 10))
b = np.eye(10, 10)

print(a)
print(a + b)

In [ ]:
# 8.
np.random.randint(0, 10, (2, 3, 4))