### 2-1 NumPy 배열 연산

In [ ]:
import numpy as np

In [ ]:
# 배열 간 연산(1차원)

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print(a1 + a2)
print(a1 - a2)
# [5 7 9]
# [-3 -3 -3]

In [ ]:
# 배열 간 연산(2차원)

a1 = np.arange(1,5).reshape(2,2)
a2 = np.arange(11,15).reshape(2,2)

print(a1)
print(a2)
# [[1 2]
#  [3 4]]
# [[11 12]
#  [13 14]]

print(a1 + a2)
# [[12 14]
#  [16 18]]

print(a2 - a1)
# [[10 10]
#  [10 10]]

In [ ]:
# 배열과 스칼라 연산(1차원)

a1 = np.array([1,2,3,4])

print(a1 + 10)
# [11 12 13 14]

print(a1 * 2)
# [2 4 6 8]

In [ ]:
# 배열과 스칼라 연산(1차원)

a1 = np.arange(1,5).reshape(2,2)
a2 = np.arange(11,15).reshape(2,2)

print(a1)
print(a2)
# [[1 2]
#  [3 4]]
# [[11 12]
#  [13 14]]

print(a1 + 5)
# [[6 7]
#  [8 9]]

print(a2 * 3)
# [[33 36]
#  [39 42]]

print(a2 / 2)
# [[5.5 6. ]
#  [6.5 7. ]]

In [ ]:
# 배열의 구조가 다른 경우

a1 = np.array([1,2,3])
a2 = np.array([1,2])

print(a1 + a2)
# ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
# 브로드캐스팅
# 자동으로 배열의 크기를 확장 -> 서로 다른 크기의 배열 간 연산을 가능하게 하는 기능
# 1. 두 배열의 차원을 뒤(낮은 차원)에서부터 비교
# 2. 크기가 같거나
# 3. 한쪽이 1인 경우 확장이 가능

a1 = np.array([[1,2,3],[4,5,6]]) # (2, 3)
a2 = np.array([10,20,30]) # (3, )

# 1차원 길이3
[10,20,30]

# 2차원으로 변혈 (1,3)
[[10,20,30]]

# 2차원의 행이 2로 확장
[[10,20,30], [10,20,30]]

print(a1 + a2)
# [[11 22 33]
#  [14 25 36]]

In [ ]:
# 브로드캐스팅 예제

a1 = np.array([[1], [2], [3]]) # (3, 1)
a2 = np.array([10,20,30]) # (3, )

# a2 : (3, ) -> (1, 3)으로 변형
[[10, 20, 30]]

# a1과 a2비교 : a1 = (3, 1), a2 = (1, 3)
# 2차원의 경우 : 3 vs 1 -> a2의 2차원이 3으로 확장
[[10, 20, 30], [10, 20, 30], [10, 20, 30]]

# 1차원의 경우 : 1 vs 3 -> a1의 1차원이 3으로 확장
[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

print(a1 + a2) 

In [ ]:
# 브로드캐스팅 불가능한 경우
a1 = np.ones((2,3))
a2 = np.ones((3,2))

print(a1 + a2)
# ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [ ]:
# 실습 1. 배열 연산
# 1.
arr = np.array([1,2,3,4])
print(arr + 3)

In [ ]:
# 2.
arr = np.array([[5,10], [15,20]])
new_arr = arr * -1
print(new_arr)

In [ ]:
# 3.
arr1 = np.array([2,4,6])
arr2 = np.array([1,2,3])
print("곱셈 :", arr1 * arr2)
print("나눗셈 :", arr1 / arr2)

In [ ]:
# 4.
arr = np.array([[95,97], [80,85]])
bc_arr = np.array([100])
print(arr + (bc_arr - arr))

In [ ]:
# 5.
arr = np.array([[1, 2, 3], [4, 5, 6]])
bc_arr = np.array([[10],[100]])
print(arr * bc_arr)

In [ ]:
# 6.
arr = np.array([[10, 20], [30, 40], [50, 60]])
bc_arr = np.array([[100], [200], [300]])
print(arr + bc_arr)

### 2-2 통계 함수 및 집계 연산

In [ ]:
# 기본 통계 함수
a = np.array([[1,2,3],[4,5,6]])

print("원소의 합 :", np.sum(a))
print("원소의 평균 :", np.mean(a))
print("표준편차 :", np.std(a))
print("최대값 :", np.max(a))
print("최소값 :", np.min(a))
print("최대값의 인덱스 :", np.argmax(a))
print("최소값의 인덱스 :", np.argmin(a))
# 원소의 합 : 21
# 원소의 평균 : 3.5
# 표준편차 : 1.707825127659933
# 최대값 : 6
# 최소값 : 1
# 최대값의 인덱스 : 5
# 최대값의 인덱스 : 0

In [ ]:
# 축(axis) 단위 연산
# axis = 0 -> 가장 높은 차원 기준 -> 행기준
    # 행기준 = 행을 따라 연산 = 행을 증가시키며 연산
# axis = 1 -> 그 다음 차원 기준 -> 열기준
    # 열기준 = 열을 따라 연산 = 열을 증가시키며 연산

a = np.array([[1,2,3],
            [4,5,6]])
print("행기준", np.sum(a, axis=0))
print("열기준", np.sum(a, axis=1))
# 행기준 [5 7 9]
# 열기준 [ 6 15]
print("행기준 평균", np.mean(a, axis=0))
print("열기준 평균", np.mean(a, axis=1))
# 행기준 평균 [2.5 3.5 4.5]
# 열기준 평균 [2. 5.]

In [ ]:
# 누적 연산
arr = np.array([1,2,3,4])
print(np.cumsum(arr)) # 누적 합
# [ 1  3  6 10]
print(np.cumprod(arr)) # 누적 곱
# [ 1  2  6 24]

In [ ]:
# 실습2. 통계 함수 및 집계 연산
# 1.
arr = np.array([5, 10, 15, 20])
print("전체 합 :", np.sum(arr))
print("평균 :", np.mean(arr))

In [ ]:
# 2.
arr = np.array([[3, 7, 1],
                [9, 2, 8]])
print("최소값 :", np.min(arr))
print("최대값 :", np.max(arr))

In [ ]:
# 3.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("열의 합 :", np.sum(arr, axis=0))
print("행의 합 :", np.sum(arr, axis=1))

In [ ]:
# 4.
arr = np.array([[10, 20],
                [30, 40],
                [50, 60]])
print("행 평균 :", np.mean(arr, axis=1))
print("열 평균 :", np.mean(arr, axis=0))

In [ ]:
# 5.
arr = np.array([2, 4, 4, 4, 5, 5, 7, 9])
print("표준편차 : ", np.std(arr))
print(arr - np.mean(arr))

In [ ]:
# 6.
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("행 누적 합 :\n", np.cumsum(arr, axis=1))
print("열 누적 곱 :\n", np.cumprod(arr, axis=0))

### 2-3 논리 연산과 조건 연산

In [ ]:
# np.where()
# 조건 기반 선택 함수

arr = np.array([10,20,30,40,50])
result = np.where(arr > 30, "high", "low")
print(result)
# ['low' 'low' 'low' 'high' 'high']

# 조건만 넣을 경우 조건을 만족하는 원소의 인덱스를 반환

arr = np.array([10,20,30,40,50])
result = np.where(arr > 30)
print(result)
# (array([3, 4]),)
print(arr[result]) # 원본 배열에 Fancy indexing
# [40 50]

In [ ]:
# 논리 연산
# and : & = 모든 조건이 True여야 True
# or : | (shift + \) = 조건 중 하나라도 True이면 True
# not : ~ = True는 False로 False는 True로

# and 연산 (&)
arr = np.array([10,20,30,40,50])
mask = (arr > 10) & (arr < 50)
print(arr[mask])
# [20 30 40]

# or 연산 (|)
mask_or = (arr < 20) | (arr > 40)
print(arr[mask_or])
# [10 50]

# not 연산 (~)
mask_not = ~(arr > 30)
print(arr[mask_not])
# [10 20 30]

In [ ]:
arr = np.arange(100)
mask = (arr % 2 == 0) & (arr > 50)
print(arr[mask])

In [ ]:
# 실습 3. 논리 연산과 조건 연산
# 1.
arr1 = np.array([5,12,18,7,30,25])
mask = (arr1 > 10) & (arr1 < 20)
print(arr1[mask])

In [ ]:
# 2.
arr2 = np.array([10,15,20,25,30,35])
result = np.where((arr2 <= 15) | (arr2 >= 30))
print(arr2[result])

In [ ]:
# 3.
arr3 = np.array([3,8,15,6,2,20])
# result = np.where(arr3 >= 10)
# arr3[result] = 0
# print(arr3)

result = np.where(arr3 >= 10, 0, arr3)
print(result)

In [ ]:
# 4.
arr4 = np.array([7,14,21,28,35])
result = np.where(arr4 >= 20, "High", "Low")
print(result)

In [ ]:
# 5.
arr5 = np.arange(10)
# result = np.where(arr5 % 2 != 0)
# arr5[result] *= 10
# print(arr5)

print(np.where(arr5 % 2 == 0, arr5, arr5 * 10))

In [ ]:
# 6.
arr6 = np.array([[10,25,30], [40,5,15], [20,35,50]])
mask = (arr6 >= 20) & (arr6 <= 40)
print(arr6[mask])

In [ ]:
# 7.
arr7 = np.array([1,2,3,4,5,6])
mask = ~(arr7 % 3 == 0)
print(arr7[mask])

In [ ]:
# 8.
arr8 = np.random.randint(0, 101, (10))
print(arr8, "\n")
# mask = arr8 < 50
# arr8[mask] = 50
# print(arr8)

print(np.where(arr8 >= 50, arr8, 50))

In [ ]:
# 9.
arr9 = np.array([[5,50,95], [20,75,10], [60,30,85]])
result = np.where(arr9 >= 70, "A", np.where(arr9 >= 30, "B", "C"))
print(result)

### 2-4 행렬의 곱셈
- 두 행렬을 곱해서 새로운 행렬을 생성하는 연산
- 첫번째 행렬의 열수와 두번째 행렬의 행수가 같아야 곱셈이 가능
- np.dot(), np.matmul() -> 행렬의 곱셈의 경우 matmul() 사용을 권장

In [ ]:
# np.dot(a, b) : 배열의 내적 연산

# 스칼라 연산 (0 D)
a = np.array(3)
b = np.array(4)

print(np.dot(a, b)) # 12

In [ ]:
# 1차원 배열간 연산 -> 내적 연산
# 데이터분석에서 벡터란 배열

a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.dot(a, b)) # 32

# 물건 구매
c = [1000,2000,5000,10000]
d = [10,3,5,7]

print(np.dot(c, d)) # 111000

In [ ]:
# 2차원 배열간 연산 -> 행렬 곱셈

a = np.array([[1,2,3], [4,5,6]])
b = np.array([[1,2], [3,4], [5,6]])

print(np.dot(a, b))
# [[22 28]
#  [49 64]]

In [ ]:
# np.matmul(a, b)
# Matrix Multiplication
# 스칼라 연산 시도시 에러

a = np.array(3)
b = np.array(4)

print(np.matmul(a, b))
# ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
# 1차원 배열간 연산 -> 내적 계산

a = np.array([1,2])
b = np.array([3,4])

print(np.matmul(a, b)) # 11

In [ ]:
# 2차원 배열간 연산 -> 행렬 곱셈

a = np.array([[1,2,3], [4,5,6]])
b = np.array([[1,2], [3,4], [5,6]])

print(np.matmul(a, b))
# [[22 28]
#  [49 64]]

# 2D * 1D 간 연산 가능
c = np.array([[1,2], [3,4]])
d = np.array([5,6])
print(np.matmul(c, d))
# [17 39]
print(np.matmul(d, c))
# [23 34]

# a x b 배열과 b x c 배열의 연산결과 = a x c로 나옴
e = np.array([[1,2,3]])
f = np.array([[1,2], [3,4], [5,6]])
print(np.matmul(e, f))
# [[22 28]]
# @ 연산자
print(e @ f)
# [[22 28]]


[[22 28]
 [49 64]]
[17 39]
[23 34]
[[22 28]]
[[22 28]]


In [117]:
# 실습 4. 행렬 곱셈
# 1.
a = np.arange(1,10).reshape(3,3)
b = np.full((3,2), 2)
print(a @ b)

[[12 12]
 [30 30]
 [48 48]]


In [105]:
# 2.
i = np.eye(4)
m = np.random.randint(0,10,(4,4))
print(m)
print(i @ m)

[[2 2 1 3]
 [4 7 1 8]
 [9 6 8 8]
 [8 4 0 3]]
[[2. 2. 1. 3.]
 [4. 7. 1. 8.]
 [9. 6. 8. 8.]
 [8. 4. 0. 3.]]


In [107]:
# 3.
x = np.ones((2,5))
y = np.arange(5,15).reshape(5,2)
print(x @ y)

[[45. 50.]
 [45. 50.]]


In [108]:
# 4.
c = np.random.randint(0,5,(3,2))
d = np.random.randint(0,5,(2,3))
result = c @ d
print(result.shape, "\n", result)

(3, 3) 
 [[ 0  9  5]
 [ 0 12  8]
 [ 0 12 10]]
