## NumPy 3

### 3-1 배열의 형태 변형과 차원 확장/축소

In [1]:
import numpy as np

In [ ]:
# array.ravel()
# 다차원 배열을 1차원 배열로 펼침
# 결과를 View로 반환(View를 변경시 원본도 변경)

a = np.array([[1,2,3], [4,5,6]])
print(a)
# [[1 2 3]
#  [4 5 6]]
flat = a.ravel()
print(flat)
# [1 2 3 4 5 6]
flat[2] = 100
print(flat)
# [  1   2 100   4   5   6]
print(a)
# [[  1   2 100]
#  [  4   5   6]]

In [ ]:
# array.flatten()
# 다차원 배열을 1차원 배열로 펼침
# 결과를 복사본으로 반환(복사본 변경시 원본은 변경되지 않음)

a = np.array([[1,2], [3,4], [5,6], [7,8]])
print(a)
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]
flat = a.flatten()
print(flat)
# [1 2 3 4 5 6 7 8]
flat[4] = 0
print(flat)
# [1 2 3 4 0 6 7 8]
print(a)
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

In [ ]:
# np.expand_dims(a, axis)
# 지정한 위치에 차원 추가(차원 확장)
# 추가되는 차원은 1차원

a = np.array([[1,2,3], [4,5,6]]) # 2 x 3
print(a.shape)
# (2, 3)

# axis=0
a0 = np.expand_dims(a, axis=0)
print(a0.shape)
# (1, 2, 3)
print(a0)
# [[[1 2 3]
#   [4 5 6]]]

# axis=1
a1 = np.expand_dims(a, axis=1)
print(a1.shape)
# (2, 1, 3)
print(a1)
# [[[1 2 3]]
# 
#  [[4 5 6]]]

# axis=2
a2 = np.expand_dims(a, axis=2)
print(a2.shape)
# (2, 3, 1)
print(a2)
# [[[1]
#   [2]
#   [3]]
# 
#  [[4]
#   [5]
#   [6]]]

In [ ]:
# np.squeeze(a, axis)
# 배열에서 크기가 1인 차원을 제거해주는 함수

a = np.array([[[[1], [2], [3]]]])

print(a.shape)
# (1, 1, 3, 1)

# axis 값 지정하지 않는 경우
s = np.squeeze(a)
print(s)
# [1 2 3]
print(s.shape)
# (3,)

In [ ]:
# axis 지정하는 경우

a2 = np.zeros((1,4,1,2))
print(a2.shape)
# (1, 4, 1, 2)

s1 = np.squeeze(a2, axis=0)
print(s1.shape)
# (4, 1, 2)

s2 = np.squeeze(a2, axis=2)
print(s2.shape)
# (1, 4, 2)

# 차원의 크기가 1이 아닌 차원은 제거할 수 없음
s3 = np.squeeze(a2, axis=1)
# ValueError: cannot select an axis to squeeze out which has size not equal to one

In [ ]:
# np.unique()
# 배열에서 중복된 요소를 제거

a = np.array([1,1,2,2,6,2,2,3,3,3,4,4,5])

u1 = np.unique(a) # 고유값의 오름차순 배열 반환
print(u1)
# [1 2 3 4 5 6]

u2, idx, inv, cnt = np.unique(a, return_index=True, return_inverse=True, return_counts=True)
print("인덱스 :", idx) # 고유값이 원본에서 처음 나타나는 인덱스
# 인덱스 : [ 0  2  7 10 12  4]
print("원본의 고유값 인덱스 :", inv)
# 원본의 고유값 인덱스 : [0 0 1 1 5 1 1 2 2 2 3 3 4]
print("값의 등장 횟수 :", cnt)
# 값의 등장 횟수 : [2 4 3 2 1 1]

In [ ]:
# 실습 1. 배열 형태 변형, 차원 확장, 축소
# 1.
arr = np.array([[10, 20], [30, 40], [50, 60]])

flat1 = arr.ravel()
flat2 = arr.flatten()
print("ravel :", flat1)
print("flatten :", flat2)

arr[0,0] = 999
print("ravel :", flat1)
print("flatten :", flat2)

In [ ]:
# 2.
img = np.random.rand(32, 32)
img_1 = np.expand_dims(img, axis=0)
print(img_1.shape)

In [ ]:
# 3.
img = np.random.randint(0, 255, (1, 28, 28, 1))
img_1 = np.squeeze(img)
print(img_1.shape)

In [ ]:
# 4.
arr = np.array([[3, 1, 2, 2],
                [1, 2, 3, 1],
                [2, 2, 1, 4]])
flat_arr = arr.flatten()
print("1. \n", flat_arr)

u_arr = np.unique(flat_arr)
print("2. \n", u_arr)
# re_arr = u_arr.reshape(1, len(u_arr))
re_arr = u_arr.reshape(1, -1) # -1을 입력할시 자동으로 계산해줌
print(re_arr)

In [ ]:
# 5.
arr = np.array([[[1], [3], [2], [1], [3], [2], [3], [1], [2], [3]]]) # shape (1, 10, 1)
s_arr = np.squeeze(arr)
print(s_arr)
u_arr = np.unique(s_arr)
print(u_arr)

In [ ]:
# 6.
arr = np.array([ [[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5]],
                [[3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8]] ]) # shape (2, 3, 4)
f_arr = arr.flatten()
print(f_arr)
u_arr = np.unique(f_arr)
re_arr = np.expand_dims(u_arr, axis=1)
print(re_arr)

### 3-2 배열의 결합과 분리

In [ ]:
# np.concatenate()
# 배열 시퀀스를 결합
# 기존 구조 안에서 결합

a = np.array([[1,2], [3,4]]) # (2, 2)
b = np.array([[5,6]])

# axis 지정하지 않을 시 기본 값 = 0
result = np.concatenate((a, b))
print(result)
# [[1 2]
#  [3 4]
#  [5 6]]
print(result.shape)
# (3, 2)

c = np.array([[7], [8], [9]])
result2 = np.concatenate((result, c), axis=1)
print(result2)
# [[1 2 7]
#  [3 4 8]
#  [5 6 9]]
print(result2.shape)
# (3, 3)

# 결합하는 axis를 제외한 나머지 차원이 같아야 결합 가능
result0 = np.concatenate((a, b), axis=1)
# ValueError

In [ ]:
# np.stack()
# 새로운 차원을 추가하면서 결합
# shape 형태가 같아야 결합 가능

a = np.array([1,2,3]) # (3,)
b = np.array([4,5,6])

# axis=0
s1 = np.stack((a,b))
print(s1)
# [[1 2 3]
#  [4 5 6]]
print(s1.shape)
# (2, 3)

# axis=1
s2 = np.stack((a,b), axis=1)
print(s2)
# [[1 4]
#  [2 5]
#  [3 6]]
print(s2.shape)
# (3, 2)

In [ ]:
# np.split()
# 배열을 여러개의 하위배열로 분할

a = np.arange(9)
s = np.split(a, 3)
print(a)
# [0 1 2 3 4 5 6 7 8]
print(s)
# [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
print(s[0])
# [0 1 2]
print(s[1])
# [3 4 5]
print(s[2])
# [6 7 8]

In [ ]:
# 배열을 같은 크기로만 나눌 수 있음

a = np.arange(9)
s = np.split(a, 4)
# ValueError: array split does not result in an equal division

In [ ]:
# 인덱스를 기준으로 분할하면 일정하지 않은 크기로 분할 가능

a = np.arange(16).reshape(4,4)
print(a)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]
#  [12 13 14 15]]

s1 = np.split(a, [1,3])
for part in s1:
    print(part)
# [[0 1 2 3]]
# [[ 4  5  6  7]
#  [ 8  9 10 11]]
# [[12 13 14 15]]

# axis=1 인 경우
s2 = np.split(a, 2, axis=1)
for part in s2:
    print(part)
# [[ 0  1]
#  [ 4  5]
#  [ 8  9]
#  [12 13]]
# [[ 2  3]
#  [ 6  7]
#  [10 11]
#  [14 15]]

In [10]:
# 실습2. 배열의 결합과 분리
# 1.
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

result = np.concatenate((a, b))
print(result)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
# 2.
a = np.arange(12)

s = np.split(a, 3)
print(s)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]


In [12]:
# 3.
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

s = np.stack((a, b, c))
print(s)
print(s.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [5]:
# 4.
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8,9], [10,11,12]])

s = np.stack((a, b), axis=0)
print(s)
print(s.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [6]:
# 5.
arr = np.arange(8)

s = np.split(arr, [2,5])
print(s)

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7])]


In [9]:
# 6.
a = np.ones((2,3))
b = np.zeros((2,3))

a0 = np.stack((a, b), axis=0)
a1 = np.stack((a, b), axis=1)
print("axis=0 :\n", a0)
print()
print("axis=1 :\n", a1)

axis=0 :
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]

axis=1 :
 [[[1. 1. 1.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [0. 0. 0.]]]


### 3-3 배열의 정렬

In [ ]:
# np.sort(array)
# 정렬된 복사본 반환

# array.sort()
# 원본 배열을 정렬

# 1 차원 배열
a = np.array([3,1,4,2])
s = np.sort(a)
print(s)
print(a)
# [1 2 3 4]
# [3 1 4 2]
a.sort()
print(a)
# [1 2 3 4]

# 내림차순 : sort한 후 배열을 뒤집어야 함
print(a[::-1])
# [4 3 2 1]

In [ ]:
# 2 차원 배열 정렬
a = [[6,5,4], [3,1,2]]

s1 = np.sort(a, axis=0)
print(s1)
# [[3 1 2]
#  [6 5 4]]

s2 = np.sort(a, axis=1)
print(s2)
# [[4 5 6]
#  [1 2 3]]

In [ ]:
# np.argsort()
# 정렬 인덱스를 반환

a = np.array([3,1,4,2])
idx = np.argsort(a)
print(idx)
# [1 3 0 2]
print(a[idx])
# [1 2 3 4]

In [ ]:
# 실습 3. 배열의 정렬
# 1.
arr = np.array([7, 2, 9, 4, 5])

s1 = np.sort(arr)
s2 = np.sort(arr)[::-1]
print(s1)
print(s2)

In [ ]:
# 2.
arr = np.array([[9, 2, 5],
                [3, 8, 1]])

s = np.sort(arr, axis=1)
print(s)

In [ ]:
# 3.
arr = np.array([10, 3, 7, 1, 9])

idx = np.argsort(arr)
print(idx)
print(arr[idx])

In [ ]:
# 4.
arr = np.array([[4, 7, 2],
                [9, 1, 5],
                [6, 8, 3]])

s = np.sort(arr, axis=0)
print(s)